import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../globals.css';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { routing } from '@/i18n/routing';
import { notFound } from 'next/navigation';
import SmoothScrolling from '@/components/SmoothScrolling';
import Header from '@/components/Header';
import Image from 'next/image';

const geistSans = localFont({
	src: '../fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: '../fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function LocaleLayout({
	children,
	params: { locale },
}: Readonly<{
	children: React.ReactNode;
	params: { locale: string };
}>) {
	// Ensure that the incoming `locale` is valid
	if (!routing.locales.includes(locale as any)) {
		notFound();
	}

	// Providing all messages to the client
	// side is the easiest way to get started
	const messages = await getMessages();

	return (
		<html lang={locale}>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<NextIntlClientProvider messages={messages}>
					<Header />
					<SmoothScrolling>
						<main>{children}</main>
					</SmoothScrolling>
					<footer className='row-start-3 flex gap-6 flex-wrap items-center justify-center'>
						<a
							className='flex items-center gap-2 hover:underline hover:underline-offset-4'
							href='https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app'
							target='_blank'
							rel='noopener noreferrer'
						>
							<Image
								aria-hidden
								src='https://nextjs.org/icons/file.svg'
								alt='File icon'
								width={16}
								height={16}
							/>
							Learn
						</a>
						<a
							className='flex items-center gap-2 hover:underline hover:underline-offset-4'
							href='https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app'
							target='_blank'
							rel='noopener noreferrer'
						>
							<Image
								aria-hidden
								src='https://nextjs.org/icons/window.svg'
								alt='Window icon'
								width={16}
								height={16}
							/>
							Examples
						</a>
						<a
							className='flex items-center gap-2 hover:underline hover:underline-offset-4'
							href='https://nextjs.org?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app'
							target='_blank'
							rel='noopener noreferrer'
						>
							<Image
								aria-hidden
								src='https://nextjs.org/icons/globe.svg'
								alt='Globe icon'
								width={16}
								height={16}
							/>
							Go to nextjs.org →
						</a>
					</footer>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
